"""Models capturing agent execution provenance, tool calls, and staged draft artifacts."""

from datetime import datetime, timezone
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field
import uuid

from gxpsoft.core.crypto import compute_sha256


class ToolCall(BaseModel):
    """Execution record of an external tool/MCP invocation."""
    tool_call_id: str = Field(default_factory=lambda: f"TCL-{uuid.uuid4().hex[:8].upper()}")
    agent_run_id: str
    tool_name: str
    tool_version: str = Field(default="1.0")
    request_payload: Dict[str, Any]
    response_payload: Dict[str, Any]
    policy_decision: str = Field(default="ALLOWED", description="Policy engine check result")
    latency_ms: int = Field(default=0)
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class AgentRun(BaseModel):
    """Complete provenance of an agent execution."""
    run_id: str = Field(default_factory=lambda: f"RUN-{uuid.uuid4().hex[:8].upper()}")
    case_id: str
    agent_name: str
    agent_version: str
    model_name: str
    prompt_version: str
    prompt_hash: str
    input_payload: Dict[str, Any]
    input_hash: str = Field(default="")
    output_payload: Dict[str, Any] = Field(default_factory=dict)
    output_hash: str = Field(default="")
    status: str = Field(default="COMPLETED")
    latency_ms: int = Field(default=0)
    token_usage: Dict[str, int] = Field(default_factory=dict)
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    completed_at: Optional[datetime] = None

    def model_post_init(self, __context: Any) -> None:
        if not self.input_hash and self.input_payload:
            self.input_hash = compute_sha256(self.input_payload)
        if not self.output_hash and self.output_payload:
            self.output_hash = compute_sha256(self.output_payload)


class DraftArtifact(BaseModel):
    """Staged draft artifact generated by an agent for human review."""
    artifact_id: str = Field(default_factory=lambda: f"ART-{uuid.uuid4().hex[:8].upper()}")
    case_id: str
    agent_run_id: str
    artifact_type: str = Field(description="e.g. INVESTIGATION_REPORT, RCA_5WHY, CAPA_PLAN, SOP_REDLINE")
    title: str
    structured_content: Dict[str, Any] = Field(description="Structured fields of the proposed report")
    claim_ids: List[str] = Field(default_factory=list, description="IDs of claims incorporated in draft")
    version: int = Field(default=1)
    status: str = Field(default="STAGED_FOR_REVIEW", description="STAGED_FOR_REVIEW, ACCEPTED, MODIFIED, REJECTED")
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
